name: Auto sign up juejin!

on:
  schedule:
    - cron: "25 * * * *"

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
      - name: Run Project
        run: |
          pnpm i
          pnpm test
