name: Auto sign up juejin!

on:
  schedule:
    - cron: "25 * * * *"

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd src
          node index.js
