name: Auto sign up juejin!

on:
  schedule:
    - cron: "52 * * * *"

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
      - name: Run Project
        run: |
          npm install
          npm run test
